### PR TITLE
version 1.0.5

### PR DESCRIPTION
**Pull request by said9999**
summary: version 1.0.5

description: change readme, podfile, and a sdk bug

Test plan: local test. unit test pass

### CODE REVIEW

**Comment by jasonpeng** [comment]
@said9999 please rebase this pull request on the master branch

**Comment by jasonpeng** [comment]
@said9999 and take a look at yulu's commits for 1.0.4 release

**Comment by said9999** [comment]
Hi Pengjun,

I have merge the code, pls help me check.
1.0.4 can be installed now. just check if the tag is on the correct commit.

Cheers,
Yaoxuan Jiang

**Comment by jasonpeng** [comment]
you need to base your changes on this commit: https://github.com/visenze/visearch-sdk-ios/commit/30463c4c192771fd43b95377aab0b934227dab48

**Pull request merged**
